1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
import numpy as np

In [3]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [4]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [5]:
n = len(X)
n

10

In [6]:
b = (np.mean(X * y) - np.mean(X) * np.mean(y)) / (np.mean(X ** 2) - np.mean(X) ** 2)
b

2.620538882402765

In [7]:
a = np.mean(y) - b * np.mean(X)
a

444.1773573243596

In [8]:
X = X.reshape(10, 1)
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [9]:
y = y.reshape(10, 1)
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [10]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([[5.88982042]])

In [11]:
X = np.hstack([np.ones((10, 1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [12]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([[444.17735732],
       [  2.62053888]])

2. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

In [13]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [14]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [17]:
def mse_(B1, y = y, X = X, n = 10):
    return np.sum((B1 * X - y) ** 2) / n

In [40]:
B1 = 0.1
alpha = 0.00001

In [41]:
for i in range (100):
    B1 -= alpha * (2 / n) * np.sum((B1 * X - y) * X)
    if i % 5 == 0:
        print('i=', i, ' B1=', B1, ' mse=', mse_(B1))

i= 0  B1= 1.6952808000000004  mse= 298904.5992334053
i= 5  B1= 5.0527146463278365  mse= 66170.75681374483
i= 10  B1= 5.722758921136703  mse= 56901.35704574499
i= 15  B1= 5.856479896963282  mse= 56532.17235319795
i= 20  B1= 5.883166639986514  mse= 56517.468344241344
i= 25  B1= 5.888492522846594  mse= 56516.88270815252
i= 30  B1= 5.889555411195862  mse= 56516.859383246396
i= 35  B1= 5.8897675322042815  mse= 56516.8584542544
i= 40  B1= 5.88980986526988  mse= 56516.858417254174
i= 45  B1= 5.889818313694939  mse= 56516.858415780545
i= 50  B1= 5.889819999750153  mse= 56516.85841572186
i= 55  B1= 5.889820336236795  mse= 56516.85841571949
i= 60  B1= 5.889820403389555  mse= 56516.85841571941
i= 65  B1= 5.889820416791255  mse= 56516.8584157194
i= 70  B1= 5.8898204194658375  mse= 56516.85841571941
i= 75  B1= 5.889820419999605  mse= 56516.8584157194
i= 80  B1= 5.889820420106129  mse= 56516.8584157194
i= 85  B1= 5.889820420127388  mse= 56516.85841571941
i= 90  B1= 5.88982042013163  mse= 56516.85841